version: 3

tasks:
  run:
    desc: Starts GQL server with playground
    cmds:
      - go run ./main.go

  generate:
    desc: Generates code based on GQL schema and Protobuf files
    cmds:
      - gqlgen generate
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=require_unimplemented_servers=false:. --go-grpc_opt=paths=source_relative internal/protos/*.proto