// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: internal/protos/game-collection.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *FindGameRequest) Reset() {
	*x = FindGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_game_collection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindGameRequest) ProtoMessage() {}

func (x *FindGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_game_collection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindGameRequest.ProtoReflect.Descriptor instead.
func (*FindGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_game_collection_proto_rawDescGZIP(), []int{0}
}

func (x *FindGameRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type FindGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games []*Game `protobuf:"bytes,1,rep,name=Games,proto3" json:"Games,omitempty"`
}

func (x *FindGameResponse) Reset() {
	*x = FindGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_game_collection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindGameResponse) ProtoMessage() {}

func (x *FindGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_game_collection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindGameResponse.ProtoReflect.Descriptor instead.
func (*FindGameResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_game_collection_proto_rawDescGZIP(), []int{1}
}

func (x *FindGameResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type GetGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetGameRequest) Reset() {
	*x = GetGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_game_collection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRequest) ProtoMessage() {}

func (x *GetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_game_collection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRequest.ProtoReflect.Descriptor instead.
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_game_collection_proto_rawDescGZIP(), []int{2}
}

func (x *GetGameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_protos_game_collection_proto protoreflect.FileDescriptor

var file_internal_protos_game_collection_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x2f, 0x0a,
	0x10, 0x46, 0x69, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x05, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x20,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64,
	0x32, 0x98, 0x01, 0x0a, 0x0e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x05, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64,
	0x47, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protos_game_collection_proto_rawDescOnce sync.Once
	file_internal_protos_game_collection_proto_rawDescData = file_internal_protos_game_collection_proto_rawDesc
)

func file_internal_protos_game_collection_proto_rawDescGZIP() []byte {
	file_internal_protos_game_collection_proto_rawDescOnce.Do(func() {
		file_internal_protos_game_collection_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_game_collection_proto_rawDescData)
	})
	return file_internal_protos_game_collection_proto_rawDescData
}

var file_internal_protos_game_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_protos_game_collection_proto_goTypes = []interface{}{
	(*FindGameRequest)(nil),  // 0: game_collection.FindGameRequest
	(*FindGameResponse)(nil), // 1: game_collection.FindGameResponse
	(*GetGameRequest)(nil),   // 2: game_collection.GetGameRequest
	(*Game)(nil),             // 3: Game
}
var file_internal_protos_game_collection_proto_depIdxs = []int32{
	3, // 0: game_collection.FindGameResponse.Games:type_name -> Game
	2, // 1: game_collection.GameCollection.GetGame:input_type -> game_collection.GetGameRequest
	0, // 2: game_collection.GameCollection.FindGame:input_type -> game_collection.FindGameRequest
	3, // 3: game_collection.GameCollection.GetGame:output_type -> Game
	1, // 4: game_collection.GameCollection.FindGame:output_type -> game_collection.FindGameResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protos_game_collection_proto_init() }
func file_internal_protos_game_collection_proto_init() {
	if File_internal_protos_game_collection_proto != nil {
		return
	}
	file_internal_protos_game_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_game_collection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_game_collection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_game_collection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_game_collection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_game_collection_proto_goTypes,
		DependencyIndexes: file_internal_protos_game_collection_proto_depIdxs,
		MessageInfos:      file_internal_protos_game_collection_proto_msgTypes,
	}.Build()
	File_internal_protos_game_collection_proto = out.File
	file_internal_protos_game_collection_proto_rawDesc = nil
	file_internal_protos_game_collection_proto_goTypes = nil
	file_internal_protos_game_collection_proto_depIdxs = nil
}
